namespace:
  name: "front-end-qa-namespace"
  defaultNamespace: "front-end-qa-namespace"

app:
  deploymentName: "frontend-deployment"
  replicaCount: 2
  env: front-end

# ── Image ────────────────────────────────────────────
image:
  containerName: "frontend-container"
  repository: "mahesh032/angular-web-app"
  tag: 71
  pullPolicy: IfNotPresent
  containerPort: 3000

# ── Deployment Strategy ──────────────────────────────
strategy:
  type: RollingUpdate          # RollingUpdate | Recreate
  rollingUpdate:
    maxSurge: 1                # how many extra pods during upgrade
    maxUnavailable: 0          # zero downtime

# ── Resources ────────────────────────────────────────
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

# ── Pod Security Context (pod level) ─────────────────
podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
  fsGroup: 2000
  seccompProfile:          # ← missing here
    type: RuntimeDefault

# ── Container Security Context (container level) ─────
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  #  readOnlyRootFilesystem: true  #TODO ← can cause app failures
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL


# ── Service ──────────────────────────────────────────
service:
  enabled: true
  serviceApp: "frontend-service"
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 32201              # range 30000–32767

