---
# Source: backend/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: back-end-qa-namespace
  annotations:
    meta.helm.sh/release-name: qa-deployment
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/enforce: restricted   # strictest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Source: backend/templates/network-policy.yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: application-network-policy
  namespace: back-end-qa-namespace
spec:
  podSelector:
    matchLabels:
      app: app-label
      env: dev
  policyTypes:
    - Ingress
    - Egress
---
# Source: backend/templates/resourceQuota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-with-limits
  namespace: back-end-qa-namespace
spec:
  hard:
    pods: "100"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
---
# Source: backend/templates/max-pbd.yml
# TODO PodDisruptionBudget (PDB) is a Kubernetes resource that ensures a specified minimum  number of pods remain available during voluntary disruptions, such as node maintenance, upgrades, or scaling operations
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb-max
  namespace: back-end-qa-namespace
spec:
  maxUnavailable: 3
  selector:
    matchLabels:
      app: app-label
      env: dev
---
# Source: backend/templates/min-pbd.yml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb-min
  namespace: back-end-qa-namespace
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-label
      env: dev #TODO -> Label to identify the backend service pods and should match the labels used in the Deployment |
---
# Source: backend/templates/serviceconnection.yaml
---
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: my-account
   namespace: dev
   annotations:
     azure.workload.identity/client-id: c2f6168a-9f76-4e62-ab21-7dc876a89a0a
---
# Source: backend/templates/finalizers-namespace.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-finalizers
  namespace: back-end-qa-namespace
  finalizers:
    - kubernetes
data:
  env: prod
status:
  phase: Active
---
# Source: backend/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  namespace: back-end-qa-namespace
  labels:
    app: app-label
    env: dev
spec:
  selector:
    matchLabels:
      app: app-label
      env: dev
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-label
        env: dev
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000 # <-- This is the pod user ID
        runAsGroup: 3000
      containers:
        - name: springbootcontainer
          image: "srinu641/spring-application-k8s:v3.0" #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: Always
          ports:
            - containerPort: 1199
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
# Source: backend/templates/haproxy-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-proxy-deployment
  namespace: back-end-qa-namespace
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  ingressClassName: haproxy
  rules:
    - host: viveja.com # TODO WILD CARD DOMAIN -> "*.domain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 1199
---
# Source: backend/templates/keda-hpa.yaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: backend-hpa
  namespace: back-end-qa-namespace
spec:
  hosts:
    - myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-end
    service: backend-service
    port: 1199
  replicas:
    min: 1
    max: 10
