---
# Source: backend/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: back-end-qa-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: qa-deployment
    meta.helm.sh/release-namespace: default
---
# Source: backend/templates/resourceQuota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-with-limits
  namespace: back-end-qa-namespace
spec:
  hard:
    pods: "100"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
---
# Source: backend/templates/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: back-end-qa-namespace
spec:
  limits:
    - type: Container
      max:
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "64Mi"
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
---
# Source: backend/templates/max-pbd.yml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb-max
  namespace: back-end-qa-namespace
spec:
  maxUnavailable: 3
  selector:
    matchLabels:
      app: app-label
      env: dev
---
# Source: backend/templates/min-pbd.yml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb-min
  namespace: back-end-qa-namespace
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-label
      env: dev #TODO -> Label to identify the backend service pods and should match the labels used in the Deployment |
---
# Source: backend/templates/finalizers-namespace.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-finalizers
  namespace: back-end-qa-namespace
  finalizers:
    - kubernetes
data:
  env: prod
status:
  phase: Active
---
# Source: backend/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  namespace: back-end-qa-namespace
  labels:
    app: app-label
    env: dev
spec:
  selector:
    matchLabels:
      app: app-label
      env: dev
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-label
        env: dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # <-- This is the pod user ID
        runAsGroup: 3000
      containers:
        - name: springbootcontainer
          image: "srinu641/spring-application-k8s:v3.0" #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: Always
          ports:
            - containerPort: 1199
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
# Source: backend/templates/keda-hpa.yaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: backend-hpa
  namespace: back-end-qa-namespace
spec:
  hosts:
    - myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-end
    service: backend-service
    port: 1199
  replicas:
    min: 1
    max: 10
