---
# Source: backend/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: app-label
    env: dev
spec:
  type: NodePort
  selector:
    app: app-label
    env: dev
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 1199
---
# Source: backend/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: app-label
    env: dev
spec:
  selector:
    matchLabels:
      app: app-label
      env: dev
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-label
        env: dev
    spec:
      containers:
        - name: springbootcontainer
          image: "srinu641/spring-application-k8s:v1.02" #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: Always
          ports:
            - containerPort: 1199
          resources:
            requests:
            limits:
              cpu: 500m
              memory: 356Mi
            requests:
              cpu: 10m
              memory: 64Mi

