---
# Source: backend/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: back-end-dev-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/enforce: restricted   # strictest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    meta.helm.sh/release-name: dev-deployment
    meta.helm.sh/release-namespace: default
---
# Source: backend/templates/max-pbd.yml
# TODO PodDisruptionBudget (PDB) is a Kubernetes resource that ensures a specified minimum  number of pods remain available during voluntary disruptions, such as node maintenance, upgrades, or scaling operations
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb-max
  namespace: back-end-dev-namespace
spec:
  maxUnavailable: 4
  selector:
    matchLabels:
      app: app-label
      env: dev
---
# Source: backend/templates/min-pbd.yml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb-min
  namespace: back-end-dev-namespace
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: app-label
      env: dev #TODO -> Label to identify the backend service pods and should match the labels used in the Deployment |
---
# Source: backend/templates/serviceconnection.yaml
---
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: my-account
   namespace: dev
   annotations:
     azure.workload.identity/client-id: c2f6168a-9f76-4e62-ab21-7dc876a89a0a
---
# Source: backend/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  namespace: back-end-dev-namespace
  labels:
    app: app-label
    env: dev
spec:
  selector:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000 # <-- This is the pod user ID
      runAsGroup: 
    matchLabels:
      app: app-label
      env: dev
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-label
        env: dev
    spec:
      containers:
        - name: springbootcontainer
          image: "srinu641/spring-application-k8s:v3.0" #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: Always
          ports:
            - containerPort: 1199
          resources:
            requests:
              cpu: "400m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "356Mi"
---
# Source: backend/templates/haproxy-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-proxy-deployment
  namespace: back-end-dev-namespace
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  ingressClassName: haproxy
  rules:
    - host: viveja.com # TODO WILD CARD DOMAIN -> "*.domain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 1199
---
# Source: backend/templates/keda-hpa.yaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: backend-hpa
  namespace: back-end-dev-namespace
spec:
  hosts:
    - myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-end
    service: backend-service
    port: 1199
  replicas:
    min: 1
    max: 10
