---
# Source: backend/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: back-end-qa-namespace
  annotations:
    meta.helm.sh/release-name: qa-deployment
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/enforce: restricted   # strictest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Source: backend/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: application-network-policy
  namespace: back-end-qa-namespace
spec:
  podSelector:
    matchLabels:
      app: app-label
      env: dev
  policyTypes:
    - Ingress
    - Egress
---
# Source: backend/templates/resourceQuota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-with-limits
  namespace: back-end-qa-namespace
spec:
  hard:
    pods: "100"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
---
# Source: backend/templates/serviceconnection.yaml
#TODO Azure Disk - Standard HDD (Managed)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-standard
  labels:
    app: app-label
    env: dev
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuName: Standard_LRS
  kind: Managed
  resourceGroup: my-aks-resource-group
  subscriptionID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
---
# Source: backend/templates/serviceconnection.yaml
# Azure Disk - Premium SSD
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-premium
  labels:
    app: app-label
    env: dev
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuName: Premium_LRS
  kind: Managed
  cachingMode: ReadOnly
  resourceGroup: my-aks-resource-group
---
# Source: backend/templates/serviceconnection.yaml
# Azure File Share - SMB (Workload Identity)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-smb
  labels:
    app: app-label
    env: dev
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
  # Workload Identity (Recommended for AKS)
  azureStorageAuthType: workloadIdentity
  azureStorageAccountName: myaksstore
  azureStorageAccountNamespace: default
  resourceGroup: my-aks-resource-group
  subscriptionID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  tenantID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
---
# Source: backend/templates/serviceconnection.yaml
# Azure File Share - NFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-nfs
  labels:
    app: app-label
    env: dev
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  skuName: Premium_LRS
  protocol: nfs
  azureStorageAuthType: workloadIdentity
  resourceGroup: my-aks-resource-group
  subscriptionID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
---
# Source: backend/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  namespace: back-end-qa-namespace
  labels:
    app: app-label
    env: dev
spec:
  selector:
    matchLabels:
      app: app-label
      env: dev
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-label
        env: dev
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault   # ← pod level
      containers:
        - name: springbootcontainer
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault  # ← container level
          image: "srinu641/spring-application-k8s:V2.0"  #TODO ->< IMAGE NAME AND TAGS
          imagePullPolicy: Always
          ports:
            - containerPort: 1199
          resources:
            requests:
              cpu: "300m"
              memory: "328Mi"
            limits:
              cpu: "500m"
              memory: "600Mi"
---
# Source: backend/templates/haproxy-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-proxy-deployment
  namespace: back-end-qa-namespace
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  ingressClassName: haproxy
  rules:
    - host: viveja.com # TODO WILD CARD DOMAIN -> "*.domain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 1199
---
# Source: backend/templates/max-pbd.yml
# TODO PodDisruptionBudget (PDB) is a Kubernetes resource that ensures a specified minimum  number of pods remain available during voluntary disruptions, such as node maintenance, upgrades, or scaling operations
---
# Source: backend/templates/keda-hpa.yaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: backend-hpa
  namespace: back-end-qa-namespace
spec:
  hosts:
    - myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-end
    service: backend-service
    port: 1199
  replicas:
    min: 1
    max: 10
