---
# Source: front-end/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: front-end-prod-namespace
  labels:
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/enforce: restricted   # strictest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    meta.helm.sh/release-name: frontend-prod-deployment
    meta.helm.sh/release-namespace: default
---
# Source: front-end/templates/service.yaml
# ← will work now
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: front-end-prod-namespace
  labels:
        app: frontend
        env: front-end
spec:
  type: NodePort
  selector:
        app: frontend
        env: front-end
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 32203
---
# Source: front-end/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: front-end-prod-namespace
  labels:
    app: frontend
    env: front-end
spec:
  selector:
    matchLabels:
      app: frontend
      env: front-end
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
        env: front-end
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault   # ← pod level
      containers:
        - name: frontend-container
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000  # ← container level
          image: "mahesh032/angular-web-app:71"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
