apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-azure-disk
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  kind: Managed
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-azure-disk
  resources:
    requests:
      storage: 20Gi

---
volumeMounts:
  - name: mysql-storage
    mountPath: /var/lib/mysql

volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc

---