 {{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace.name }}
  spec:
    provider: {{ .Values.secrets.provider }}
    parameters:
      useVMManagedIdentity: "true"
      userAssignedIdentityID: {{ .Values.secrets.managedIdentity.clientId }}
      keyvaultName: {{ .Values.secrets.keyVaultName }}
      tenantId: {{ .Values.secrets.tenantId }}
      objects: |
        array:
        {{- range .Values.secrets.KeySecrets }}
          - |
            objectName: {{ .objectName }}  
            objectType: {{ .objectType }}
        {{- end }}
       {{- end }}

---