 {{- if (.Values.keda.enabled | default false) }}
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: nginx-http-scaledobject
  namespace: {{ .Values.namespace.name }}
spec:
  host: myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    deployment: {{ .Values.deploymentName }}
    service: {{ .Values.service.serviceApp }}
    port: 1199
  replicas:
    min: {{ .Values.hpa.minReplicas }}
    max: {{ .Values.hpa.maxReplicas }}
     {{- end }}