 {{- if .Values.keda.enabled  }}
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: {{ .Values.keda.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
    - myhost.com
  targetPendingRequests: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deploymentName }}
    service: {{ .Values.service.serviceApp }}
    port: 1199
  replicas:
    min: {{ .Values.keda.minReplicas }}
    max: {{ .Values.keda.maxReplicas }}
     {{- end }}
---

