 {{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    {{- include "app-label" . | nindent 4 }}
  policyTypes:
    - Ingress
    - Egress
     {{- end }}

---