 {{- if .Values.PersistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.serviceAccount.name }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.storage }}
       {{- end }}

---