 {{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceQuota.name }}
  namespace: {{- if .Values.namespace.enabled }}
     {{ .Values.namespace.name }}
   {{- else -}}
     {{ .Release.Namespace }}
   {{- end }}
spec:
  hard:
    pods: {{ .Values.resourceQuota.hard.pods | quote }}
    requests.cpu: {{ .Values.resourceQuota.hard.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.hard.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.hard.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.hard.limitsMemory | quote }}
     {{- end }}
---