 {{- if .Values.serviceAccount.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .Values.serviceAccount.name }}
   namespace: {{ .Values.namespace.name }}
provisioner: {{ .Values.serviceAccount.provisioner }}
allowVolumeExpansion: {{ .Values.serviceAccount.allowVolumeExpansion }}
parameters:
  skuName: {{ .Values.serviceAccount.skuName }}
  azureStorageAuthType: {{ .Values.serviceAccount.azureStorageAuthType }}
reclaimPolicy: {{ .Values.serviceAccount.reclaimPolicy }}
volumeBindingMode: Immediate
 {{- end }}

---

---
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: my-account
   namespace: dev
   annotations:
     azure.workload.identity/client-id: c2f6168a-9f76-4e62-ab21-7dc876a89a0a

---
