apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pods
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-azfileshare-pods