appName: backend
env: dev
argoNamespace: argocd
project: default

repoURL: https://github.com/Srinu-rj/helm-kubernetes
targetRevision: master
chartPath: helm-charts/backend
helmValuesFile: values-dev.yaml

destServer: https://kubernetes.default.svc
destNamespace: back-end-dev-namespace

syncPolicy:
  prune: true
  selfHeal: true
  createNamespace: true