appName: backend
env: prod
argoNamespace: argocd
project: default

repoURL: https://github.com/Srinu-rj/helm-kubernetes
targetRevision: master
chartPath: helm-charts/backend
helmValuesFile: values-prod.yaml

destServer: https://kubernetes.default.svc
destNamespace: back-end-prod-namespace

syncPolicy:
  prune: true
  selfHeal: true
  createNamespace: true