appName: backend
env: qa
argoNamespace: argocd
project: default

repoURL: https://github.com/Srinu-rj/helm-kubernetes
targetRevision: master
chartPath: helm-charts/backend
helmValuesFile: values-qa.yaml

destServer: https://kubernetes.default.svc
destNamespace: back-end-qa-namespace

syncPolicy:
  prune: true
  selfHeal: true
  createNamespace: true