 {{- if .Values.service.enabled }}          # ← will work now
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceApp }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "frontend" .| nindent 8 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "frontend" .| nindent 8 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
       {{- end }}

---