apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}-{{ .Values.env }}
  namespace: {{ .Values.argoNamespace | default "argocd" }}
spec:
  project: {{ .Values.project | default "default" }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision | default "master" }}
    path: {{ .Values.chartPath }}
    helm:
      valueFiles:
        - {{ .Values.helmValuesFile }}
  destination:
    server: {{ .Values.destServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.destNamespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.prune | default true }}
      selfHeal: {{ .Values.syncPolicy.selfHeal | default true }}
    syncOptions:
      - CreateNamespace= {{ .Values.syncPolicy.createNamespace | default true }}

---